
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'includes/head.phtml'; ?>
  </head>
<body>


    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="large-12 cell">
        <?php include_once 'includes/izbornik.phtml' ?>
          
        </div>
        <?= $sadrzaj?><?php include_once 'includes/podnozje.phtml' ?>
      </div>      
    </div>


    
    <?php include_once 'includes/skripte.phtml' ?>
  </body>
</html>
