<a href="<?=App::config('url')?>polaznik/novi" 
class="success button expanded">
    Dodaj novog polaznika
</a>

<form action="" method="get">
    <input type="text" name="uvjet"
    placeholder="dio imena, prezimena ili OIB-a"
    value="<?=$uvjet?>" >
</form>
<?php include 'stranicenje.phtml' ?>
<div class="grid-x grid-padding-x">
    <?php foreach($podaci as $red): ?>
        <div class="large-3 medium-6 small-12 cell">
            <div class="callout">
                <img src="<?=App::config('url')?>public/img/nepoznato.png" 
                alt="<?=$red->ime?> <?=$red->prezime?>">

                <p><?=$red->ime?> <?=$red->prezime?></h1><hr>
                <?php
                $par=['polaznik', $red->ime . ' ' . $red->prezime, $red->clan==0];
                include BP_APP . 'view/includes/promjenabrisanje.phtml';
                ?>
            </div>
        </div>
    <?php endforeach;?>
</div>


<?php include 'stranicenje.phtml' ?>